### ISSUE TITLE
Add Docstrings to Simulation, Normalization, Metrics, and Mesh Modules

### ISSUE THREAD

**Issue by TarikKaanKoc** [IBM/simulai#102]
Currently, the Simulation, Normalization, Metrics, and Mesh modules in our codebase lack docstrings. Docstrings are essential for documenting the purpose, inputs, outputs, and usage of functions and classes. They provide a quick reference for other developers to understand and use the code. Therefore, it's important to have docstrings for all public functions and classes in our modules.

This issue is to add numpy-style docstrings to the public functions and classes in the Simulation, Normalization, Metrics, and Mesh modules. The docstrings should follow the numpydoc format and include the following sections:

* Summary: A brief one-line summary of the function/class.
* Parameters: Description of each parameter with its type, name, and description.
* Returns: Description of the return value with its type and description.
* Raises: Description of the exceptions that can be raised.
* Examples: Examples of how to use the function/class.

### We need to add docstrings to the following modules:

- [x] Simulation
- [x] Normalization
- [x] Metrics
- [x] Mesh
 
**Thank you for your contribution!**

**Comment by TarikKaanKoc** [comment]
Hi @Joao-L-S-Almeida, 

- **Can you check mesh module:** https://github.com/IBM/simulai/commit/9d4823210dd36d704e09bc55a984051dddfeb3e7

**Comment by Joao-L-S-Almeida** [comment]
That is alright, @TarikKaanKoc. Thank you.

**Comment by TarikKaanKoc** [comment]
@Joao-L-S-Almeida 
* **Can you check simulation module:** https://github.com/IBM/simulai/commit/c5cfa1cf0041dd79a512bad491810175fdfa0640
