### ISSUE TITLE
Doctrings for Optimization, SymbolicOperator and Losses

### ISSUE THREAD

**Issue by Joao-L-S-Almeida** [IBM/simulai#116]
- [x] simulai/residuals/_pytorch_residuals.py
- [x] simulai/regression/_pytorch/_dense.py
- [x] simulai/optimization/_optimization.py
- [x] simulai/optimization/_losses.py

**Comment by TarikKaanKoc** [comment]
Oiiiii @Joao-L-S-Almeida, 

I wanted to let you know that starting tomorrow evening, I will be working on updating the documentation for Optimization, SymbolicOperator, and Losses in the SimulAI project. These tasks are crucial for the development of our project and are necessary for the success of our goals.

I will be updating the documentation thoroughly to ensure that it is accurate and up-to-date. Thank you for your understanding and support.
