### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by WillTrojak** [IBM/simulai#154]
It seems that, due to the dependencies, there is a requirement that Python<3.11. Is this true?

**Comment by WillTrojak** [comment]
Ah, this only seems to be true for the current version on PyPI, the current head seems to be fine. It might be worth updating PyPI

**Comment by Joao-L-S-Almeida** [comment]
In fact, when using Python 3.11 there are issues with some versions of the basic dependencies. Nevertheless, I think it is a matter of updating the pyproject.toml file and test it in the proper environment.

**Comment by Joao-L-S-Almeida** [comment]
The process of testing have been automated via Actions, with support for Python==3.11.

**Comment by snitramodranoel** [comment]
I'm not sure PyTorch supports Python 3.11 as of now.

**Comment by Joao-L-S-Almeida** [comment]
Seemingly it doesn't broke, as seen in the ![latest test](https://github.com/IBM/simulai/actions/runs/5446722562). But I don't discard the occurrence of some warnings and issues.
