### ISSUE TITLE
Reformatter code

### ISSUE THREAD

**Issue by TarikKaanKoc** [IBM/simulai#19]
Can you share the reformatter code?

**Comment by Joao-L-S-Almeida** [comment]
Hi. Modification approved. Thank you.

Em sex, 6 de jan de 2023 14:32, Tarık Kaan Koç ***@***.***>
escreveu:

**Comment by TarikKaanKoc** [comment]
Can you take a look at the change I just made? https://github.com/IBM/simulai/pull/18

**Comment by Joao-L-S-Almeida** [comment]
I'm in agreement with the modifications.
