### ISSUE TITLE
Document editing

### ISSUE THREAD

**Issue by TarikKaanKoc** [IBM/simulai#33]
I want to edit the structure of the {sphinx_rtd_theme} document (The doc-files look pretty complex.), but haven't had the opportunity to edit it. When I run the ``make html`` command I get the following error.

```Python
make: *** No rules for making target html. Stop.
```

**Comment by Joao-L-S-Almeida** [comment]
And when executing `make docs` ? 
I agree the Sphinx configuration should be reviewed.
Would you like to be assigned to this issue, @TarikKaanKoc ?

**Comment by TarikKaanKoc** [comment]
I tried ``make clean`` and ``make docs``. It worked now.

I will fully update this docs structure.  I will try using Stanford theme.
