### ISSUE TITLE
The model called as "KoopmanOperator", in fact, should be "ExtendedOpInf"

### ISSUE THREAD

**Issue by Joao-L-S-Almeida** [IBM/simulai#34]
* Rename the occurencies.
* Verfiy the cases in `examples/`.
* Insert some sanity checks under `tests/`.

**Comment by TarikKaanKoc** [comment]
Would you check? It may be missing or incorrect.
https://github.com/IBM/simulai/pulls

**Comment by Joao-L-S-Almeida** [comment]
Issue solved. Thanks.
