### ISSUE TITLE
Upd: docs 

### ISSUE THREAD

**Issue by TarikKaanKoc** [IBM/simulai#38]
## Stanford Theme 🥇 
--- 
<img src="https://i.imgur.com/6jHaA3p.png" alt="Image description">

How do you think it looks?

**Comment by Joao-L-S-Almeida** [comment]
I think it seems magnificent. What do you think @snitramodranoel ?

**Comment by TarikKaanKoc** [comment]
If you accept, I will update the document with stanford theme @Joao-L-S-Almeida @snitramodranoel

**Comment by snitramodranoel** [comment]
I'd abstain from using any IBM trademarks because of both commercial and logo usage guidelines.

**Comment by TarikKaanKoc** [comment]
## Upd logo and contents 🥇 
--- 
<img src="https://i.imgur.com/Qx8sahk.png" alt="Image description">


@snitramodranoel @Joao-L-S-Almeida
