### ISSUE TITLE
Automatic configuration for Autoencoders

### ISSUE THREAD

**Issue by Joao-L-S-Almeida** [IBM/simulai#41]
* Intead of providing instances of sub-networks for an AE object, there could be an option for automatically instantiating them. 
* By providing an option 'auto=True', the class will call the subnetworks and provide automatically generated configuration dictionaries for them.

**Comment by TarikKaanKoc** [comment]
This is a good idea. Automatic configuration for Autoencoders can help make the process of creating and training an AE more streamlined and user-friendly.
