### ISSUE TITLE
How to properly upload docs to https://simulai-toolkit.readthedocs.io/ ?

### ISSUE THREAD

**Issue by Joao-L-S-Almeida** [IBM/simulai#45]
* It should provide the description available on README. 
* It should provide package description, module by module, displaying docstring and source code.

**Comment by TarikKaanKoc** [comment]
Ok. I will update the document.

<img src="https://i.imgur.com/Z8XiMsd.png" alt="Image description">


The quickstart content provides the content found in the readme file. I made some edits here, for example: I did not prefer the include shortcut in the quickstart.rst content to access the content in fig/.

**Comment by TarikKaanKoc** [comment]
Can you close the issues that are finished? @Joao-L-S-Almeida

**Comment by Joao-L-S-Almeida** [comment]
The docs compillation was failling because of a missing dependency. It was solved in issue #59. 
You did an excellent job when creating these docs pages @TarikKaanKoc.

**Comment by TarikKaanKoc** [comment]
> The docs compillation was failling because of a missing dependency. It was solved in issue #59.
> You did an excellent job when creating these docs pages @TarikKaanKoc.

Thank you 💙
