### ISSUE TITLE
Upd: logo

### ISSUE THREAD

**Issue by TarikKaanKoc** [IBM/simulai#47]
## New Logo🥇  (Created with Canva)
--- 
<img src="https://i.imgur.com/aKlpypd.png" alt="Image description">

**Comment by Joao-L-S-Almeida** [comment]
This is interesting, but I think we would like something more minimalistic, for example, a purely text-based logo using the right-hand side in black and red.

**Comment by Joao-L-S-Almeida** [comment]
### Maybe something like this one (created using Inkscape)![logo_3](https://user-images.githubusercontent.com/35712014/213695460-2dda8792-00d3-4e4f-8570-2d9da2aee1a5.png)

**Comment by TarikKaanKoc** [comment]
> Maybe something like this one (created using Inkscape)![logo_3](https://user-images.githubusercontent.com/35712014/213695460-2dda8792-00d3-4e4f-8570-2d9da2aee1a5.png)

Then this will be a better choice for us
