### ISSUE TITLE
PyPI project description is missing

### ISSUE THREAD

**Issue by snitramodranoel** [IBM/simulai#5]
Despite configuration of `pyproject.toml` according to `setuptools` documentation, PyPI will not render the description provided in `DESCRIPTION.md`

**Comment by Joao-L-S-Almeida** [comment]
Seemingly it is there: https://pypi.org/project/simulai-toolkit/0.99.8/

**Comment by Joao-L-S-Almeida** [comment]
Maybe we can close this issue, @snitramodranoel.
