### ISSUE TITLE
"Sub-packages" inside simulai (regression, models, ...) are not being recognized in 0.99.8. 

### ISSUE THREAD

**Issue by Joao-L-S-Almeida** [IBM/simulai#53]
Maybe the following modifications is necessary inside pyproject.toml:
```
[tool.setuptools]
packages = ['simulai']
```
Replaced by:
```
[tool.setuptools]
packages = ['simulai/regression', 'simulai/models' ...]
```
Or simply:
```
[tool.setuptools]
packages = ['simulai/*']
```

**Comment by Joao-L-S-Almeida** [comment]
The fix I found was: 
```
[tool.setuptools.packages.find]
where = ["simulai"]
```
I has worked.

**Comment by Joao-L-S-Almeida** [comment]
@TarikKaanKoc and @snitramodranoel, what do yu think this "solution":

```
[tool.setuptools]
 packages = ['simulai', 'simulai.math', 'simulai.models', 'simulai.optimization', 'simulai.regression', 'simulai. residuals', 'simulai.rom', 'simulai.sampling', 'simulai.templates', 'simulai.utilities', 'simulai.workflows']
```

**Comment by snitramodranoel** [comment]
This should not be a problem if we use the `src/simulai/` standard - this is the reason I changed the source folder in the initial release.

**Comment by TarikKaanKoc** [comment]
The solution you provided in the last code snippet will work. It specifies that all sub-packages within the 'simulai' package should be included in the package distribution. This way, when you install or distribute your package, the sub-packages ('simulai.math', 'simulai.models', etc.) will be included and should be recognized by the system.

**Comment by TarikKaanKoc** [comment]
``find_packages()`` function to automatically find all packages under a certain directory, as I previously mentioned.

```python
from setuptools import find_packages

[tool.setuptools]
packages = find_packages(include=["simulai*"])

# or
 
from setuptools import find_namespace_packages

[tool.setuptools]
packages = find_namespace_packages(include=["simulai*"])
```

Both ``find_packages()`` and ``find_namespace_packages()`` functions scan your package directory and find all packages automatically, so you don't have to list them manually. This makes your setup.py file more maintainable and less error-prone.

**Comment by Joao-L-S-Almeida** [comment]
I tested it, @TarikKaanKoc, but the problem still persisted. 
The [solution](https://github.com/IBM/simulai/blob/b2b839c3595a6dd2a68083d97e23cffa9fc648fa/pyproject.toml#L61) I found was inspired [by the pyproject.toml from Pandas](https://github.com/pandas-dev/pandas/blob/be260f1482c4695d79725a99c490f3e0a1dae0d1/pyproject.toml#L125). The source "simulai" and its sub-packages "simulai.*" are explicitly included. It worked for the last build sent to PyPI.
