### ISSUE TITLE
Docs still ignore third level of directories ("sub-sub-packages").

### ISSUE THREAD

**Issue by Joao-L-S-Almeida** [IBM/simulai#60]
For example:

```
simulai
   |- > regression
         | - > pytorch (directory) --> ignored
         | - > _opinf.py (module) --> parsed
            :
            .
```

**Comment by TarikKaanKoc** [comment]
Can you describe the problem in detail?

**Comment by Joao-L-S-Almeida** [comment]
In some cases there are sub-directories inside the sub-packages, which are not parsed by Sphinx/Read the Docs. For example, for the sub-package `regression`:
![Captura de tela de 2023-01-25 12-04-56](https://user-images.githubusercontent.com/35712014/214598788-baf53ad3-e3de-43d0-9d7b-b1670f27391e.png)
It ignores the content of the directory pytorch 
![Captura de tela de 2023-01-25 12-06-57](https://user-images.githubusercontent.com/35712014/214599102-b63d140d-a098-49b8-bc98-f77f1485eaf0.png)

**Comment by TarikKaanKoc** [comment]
@Joao-L-S-Almeida  Now I get it, can you check it out? I updated : https://github.com/IBM/simulai/pull/61

**Comment by Joao-L-S-Almeida** [comment]
Yes, @TarikKaanKoc, it works now. A similar issue occurs for simulai/models, which has a sub-directory _pytorch_models, but I think the question is answered now. Thanks.

**Comment by TarikKaanKoc** [comment]
I added it now. @Joao-L-S-Almeida #65

**Comment by Joao-L-S-Almeida** [comment]
It still does not appear in this last docs build: https://simulai-toolkit.readthedocs.io/en/latest/?badge=latest
Maybe I'm missing some detail ?
Thanks.

**Comment by TarikKaanKoc** [comment]
Did you make a build version on the readthedocs site after merging it with the pr main branch I forwarded? @Joao-L-S-Almeida

**Comment by TarikKaanKoc** [comment]
branch: #65 and #66

**Comment by TarikKaanKoc** [comment]
branch: #65

**Comment by TarikKaanKoc** [comment]
### After the document is updated, click the button here "build version"

<a href='https://www.linkpicture.com/view.php?img=LPic63d2faad7e505668833509'><img src='https://www.linkpicture.com/q/Ekran-Resmi-2023-01-27-01.11.20.png' type='image'></a>

**Comment by Joao-L-S-Almeida** [comment]
Hi. The build should occur automatically after each commit/pull request. I cannot force the build using Read the Docs I`m accessing. 
![Captura de tela de 2023-01-26 19-46-10](https://user-images.githubusercontent.com/35712014/214968213-0935df87-9bdb-4362-bac0-af2a45cd5b0f.png)

**Comment by TarikKaanKoc** [comment]
This feature is not enabled by default and to enable it:

- Readthedocs, go to the project homepage
- Select "settings" in the menu on the left.
- Go to the "Advanced Settings" tab.
- Activate the "Build on commits" option under the "Automatic Building" heading.
- Click the "Save" button.

After doing these operations, ReadTheDocs will automatically update your documents every time you commit. Did you do this?

**Comment by Joao-L-S-Almeida** [comment]
No, I still didn't. I'll configure it. The docs are now updated after your latest commits. Thanks.
