### ISSUE TITLE
Missing documentation for module parallel

### ISSUE THREAD

**Issue by TarikKaanKoc** [IBM/simulai#78]
However, upon review, I have noticed that the entire contents of the module are not being displayed in the documentation.

I need help in finding a solution to this issue,  so that the code at documantation for module parallel can be properly displayed.

<img width="1167" alt="Ekran Resmi 2023-01-29 02 59 38" src="https://user-images.githubusercontent.com/83168207/215296623-038bbd0f-d14d-479a-abae-e19218ceaba2.png">

**Comment by Joao-L-S-Almeida** [comment]
It is almost accomplished now, see commit : https://github.com/IBM/simulai/commit/a053bb06c93e75ac6d6eedb5aba35029a7ec9138.

**Comment by TarikKaanKoc** [comment]
@Joao-L-S-Almeida Thanks 🦅
