### ISSUE TITLE
📌 Problem:  Excessive Commits and Poor Release Output 🛠

### ISSUE THREAD

**Issue by TarikKaanKoc** [IBM/simulai#80]
I've found that committing too often leads to a complicated history of commits, making it difficult to track changes and understand the development process.

Consider using a rebase or merge strategy to combine multiple commits into a single well-documented commit. (I just learned about this in my own personal project.) Additionally, it's important to thoroughly test changes before creating a release to make sure it's of high quality.

**Comment by Joao-L-S-Almeida** [comment]
It is a good idea, @TarikKaanKoc . I just started to use the `rebase` approach, folllowing your advice.
