### ISSUE TITLE
📌 Problem: Lack of Detailed Release Information 🛠

### ISSUE THREAD

**Issue by TarikKaanKoc** [IBM/simulai#81]
It has been noticed that releases are often lacking in detailed information, making it difficult for stakeholders to understand the nature and scope of changes made.

To address this problem, it is recommended to provide comprehensive and clear release notes with each release. This should include:

- A list of new features and changes
- Bug fixes and performance improvements
- Known issues and limitations
- Any breaking changes and how to handle them

By providing this information, stakeholders can have a better understanding of what has been changed and what impact it will have, enabling them to make informed decisions and prepare accordingly.

- Example my project release: https://github.com/tnltk/tnltk/releases/tag/v0.1.2

- Example polars pr release:  https://github.com/pola-rs/polars/releases/tag/py-0.16.0

### Note: 
- **I would like to request to be added as an author to repository.**

**Comment by TarikKaanKoc** [comment]
@Joao-L-S-Almeida

**Comment by Joao-L-S-Almeida** [comment]
Hi, @TarikKaanKoc. These initial releases are really very poor in description. I expect to solve this question in the future ones. Your recommendations are really welcome. 

Do you mean have writing access ? I just gave it.

**Comment by TarikKaanKoc** [comment]
Hi or oi ;) @Joao-L-S-Almeida Nevertheless, I look forward to working with you and making the project even better in the future. Thanks
