### ISSUE TITLE
📌 Enhancement Request: Develop Project Roadmap

### ISSUE THREAD

**Issue by TarikKaanKoc** [IBM/simulai#83]
I would like to request the creation of a Project Roadmap issue. This will help us keep track of the project's progress and ensure that we are moving in the right direction.

Please create the issue and I will follow up by pinning it to the repository for future reference.

Thank you in advance for your efforts in this matter.

### Create new issue for roadmap and pin issuse: 
<img width="501" alt="Ekran Resmi 2023-01-31 05 42 25" src="https://user-images.githubusercontent.com/83168207/215649344-57531c8a-ce68-4400-9d77-357b2be627a7.png">

### Example Roadmap Templates:
- https://github.com/open-mmlab/mmyolo/issues
- https://github.com/kadirnar/torchyolo/issues/5

**Comment by Joao-L-S-Almeida** [comment]
HI, @TarikKaanKoc . I made a roadmap for the more significant topics we have considered right now. 
Thanks.

**Comment by TarikKaanKoc** [comment]
Great work. Thanks 🦋🦋🦋
