### ISSUE TITLE
Help: Missing Class in PyTorch Residuals Module

### ISSUE THREAD

**Issue by TarikKaanKoc** [IBM/simulai#90]
The document has been updated but the class in the PyTorch Residuals module (simulai.residuals._pytorch_residuals) is not visible.

This issue aims to investigate the reason for the class function's absence in the documentation and find a solution to make it visible.
* Find a solution to make the class visible again

### Problem: 

<img width="1418" alt="Ekran Resmi 2023-02-04 10 32 23" src="https://user-images.githubusercontent.com/83168207/216755248-e0447b54-4b3c-4262-b821-69a452e27e0c.png">

**Comment by Joao-L-S-Almeida** [comment]
Hi. Let me know if I understand properly.  Have you flawlessly build the docs locally, but it is not being updated in  RTD ?

**Comment by TarikKaanKoc** [comment]
> Hi. Let me know if I understand properly. Have you flawlessly build the docs locally, but it is not being updated in RTD ?

Hi, I will check now. I'm sorry I wasn't available because of the earthquake.

**Comment by TarikKaanKoc** [comment]
### Difficulty documenting class within function

When attempting to generate documentation with Sphinx, I am having trouble documenting a class that is defined within a function. The current setup is as follows:


```python
def SymbolicOperator(
    expressions: list = None,
    input_vars: list = None,
    output_vars: list = None,
    function: callable = None,
    gradient: callable = None,
    keys: str = None,
    inputs_key: str = None,
    processing: str = "serial",
    device: str = "cpu",
    engine: str = "torch",
    auxiliary_expressions: list = None,
    constants: dict = None,
) -> object:
    """
    Constructs a tensor operator using symbolic expressions using PyTorch or any other supported engine.

    Args:
        expressions (list, optional): List of expressions representing the operator. Defaults to None.
        input_vars (list, optional): List of input variables. Defaults to None.
        output_vars (list, optional): List of output variables. Defaults to None.
        function (callable, optional): A callable that represents the evaluation of the tensor operator. Defaults to None.
        gradient (callable, optional): A callable that represents the gradient evaluation of the tensor operator. Defaults to None.
        keys (str, optional): The keys for accessing the inputs in the input dictionary. Defaults to None.
        inputs_key (str, optional): The key for accessing the input data in the input dictionary. Defaults to None.
        processing (str, optional): The processing method to be used during the evaluation of the tensor operator. Defaults to 'serial'.
        device (str, optional): The device to be used during the evaluation of the tensor operator. Can be either 'cpu' or 'gpu'. Defaults to 'cpu'.
        engine (str, optional): The symbolic computation engine to be used. Currently supported engines are 'torch' and 'numpy'. Defaults to 'torch'.
        auxiliary_expressions (list, optional): Additional expressions that are needed to evaluate the tensor operator. Defaults to None.
        constants (dict, optional): Constants that are required during the evaluation of the tensor operator. Defaults to None.

    Returns:
        object: An instance of the SymbolicOperatorClass.
    """

    class SymbolicOperatorClass(torch.nn.Module if engine == "torch" else object):
```

### Difficulty documenting a class defined within a function

I am having trouble documenting a class that is defined within a function when generating documentation with Sphinx. To properly document a class with Sphinx, it should be defined outside the function and then its documentation should be written in a separate documentation block. This way, Sphinx can generate separate documentation for both the function and the class.

@Joao-L-S-Almeida

**Comment by TarikKaanKoc** [comment]
How about we fix this or leave it as it is? @Joao-L-S-Almeida

**Comment by Joao-L-S-Almeida** [comment]
Hi. @TarikKaanKoc.  This implementation uses a function to return the class SymbolicOperator in order to support the usage of others backends than PyTorch, however, as we are more interested in using PyTorch as foundation (and, certainly, there are better ways to support multiple engines) I will make it a simple class in a branch associeted with this issue.

**Comment by Joao-L-S-Almeida** [comment]
Give a look, @TarikKaanKoc, in the commit ef2bc63002b3b6fda186dff088f87034838d36d9 of the branch `fix/pytorch-residuals-module`, apparently it is a solution.
 In addition to the preference for PyTorch I think the factory function which was being used was not the best solution since we cannot guarantee the entire source code can be reused with  different backends as JAX and Apache MXNet, just changing the importing source.
