### ISSUE TITLE
🦋 Suggest: using black and isort before committing code 

### ISSUE THREAD

**Issue by TarikKaanKoc** [IBM/simulai#91]
As a best practice, it is recommended to run the following commands before committing code changes to ensure the code conforms to the project's code formatting standards:

```python
black . --config pyproject.toml
isort .
```
These commands respectively enforce the PEP 8 coding style guidelines (using black) and sort the import statements (using isort). This helps maintain consistency and readability across the codebase, making it easier for others to understand and review the changes.

Please consider running these commands before making a commit in future. @Joao-L-S-Almeida

**Comment by Joao-L-S-Almeida** [comment]
Great. Thank you for the suggestion, @TarikKaanKoc .
