### ISSUE TITLE
numpy.float deprecated

### ISSUE THREAD

**Issue by Joao-L-S-Almeida** [IBM/simulai#94]
The attribute numpy.float is deprecated in numpy>=1.24. It is necessary to replace all the occurencies by the builtin float.

**Comment by TarikKaanKoc** [comment]
Can you give me an example? @Joao-L-S-Almeida

**Comment by Joao-L-S-Almeida** [comment]
For example, [in this case](https://github.com/IBM/simulai/blob/547e6f017f1603e5e212ce70c35b914180887e66/simulai/optimization/_losses.py#L845).

**Comment by Joao-L-S-Almeida** [comment]
I started to replace the occurrences and (also sanity-testing) in the branch associated with this issue. Sometimes I'm excessively cautious  : ( .
